language: php

php:
  - 7.1

before_script:
  - cp .env.example .env
  - composer self-update
  - composer install --no-interaction --dev
  - mysql -e 'create database testing;'
  - php artisan key:generate
  - php artisan migrate
  - php artisan db:seed --class="DatabaseSeeder"

script:
  - mkdir -p build/logs
  - vendor/bin/phpunit --coverage-clover build/logs/clover.xml
  - vendor/bin/phpunit --coverage-clover=coverage.xml

after_script:
  - php vendor/bin/codacycoverage phpunit

after_success:
  - bash <(curl -s https://codecov.io/bash)
  - travis_retry php vendor/bin/coveralls -v

services:
  - mysql

cache:
  directories:
    - node_modules
    - vendor

